name: Test

on: [push,pull_request]

jobs:
  test-run:
    runs-on: ubuntu-20.04
    if: always()
    steps:
      - uses: actions/checkout@v2
      - name: Check for updates
        run:  sudo apt-get update
      - name: Run test script
        run:  ./test.sh
      - name: Archive results
        uses: actions/upload-artifact@v2
        with:
          name: log-file
          path: /home/runner/work/test.log
